from graph import Graph

Romania = Graph()
Romania.add_node('Arad', 366)
Romania.add_node('Bucharest', 0)
Romania.add_node('Craiova', 160)
Romania.add_node('Drobeta', 242)
Romania.add_node('Eforie', 161)
Romania.add_node('Fagaras', 176)
Romania.add_node('Giurgiu', 77)
Romania.add_node('Hirsova', 151)
Romania.add_node('Iasi', 226)
Romania.add_node('Lugoj', 244)
Romania.add_node('Mehadia', 241)
Romania.add_node('Neamt', 234)
Romania.add_node('Oradea', 380)
Romania.add_node('Pitesti', 100)
Romania.add_node('Rimnicu Vilcea', 193)
Romania.add_node('Sibiu', 253)
Romania.add_node('Timisoara', 329)
Romania.add_node('Urziceni', 80)
Romania.add_node('Vaslui', 199)
Romania.add_node('Zerind', 374)
Romania.connect('Oradea', 'Zerind', 71)
Romania.connect('Oradea', 'Sibiu', 151)
Romania.connect('Arad', 'Zerind', 75)
Romania.connect('Arad', 'Sibiu', 140)
Romania.connect('Arad', 'Timisoara', 118)
Romania.connect('Lugoj', 'Timisoara', 111)
Romania.connect('Lugoj', 'Mehadia', 70)
Romania.connect('Drobeta', 'Mehadia', 75)
Romania.connect('Drobeta', 'Craiova', 120)
Romania.connect('Rimnicu Vilcea', 'Craiova', 146)
Romania.connect('Pitesti', 'Craiova', 138)
Romania.connect('Rimnicu Vilcea', 'Pitesti', 97)
Romania.connect('Rimnicu Vilcea', 'Sibiu', 80)
Romania.connect('Fagaras', 'Sibiu', 99)
Romania.connect('Fagaras', 'Bucharest', 211)
Romania.connect('Pitesti', 'Bucharest', 101)
Romania.connect('Giurgiu', 'Bucharest', 90)
Romania.connect('Urziceni', 'Bucharest', 85)
Romania.connect('Urziceni', 'Hirsova', 98)
Romania.connect('Eforie', 'Hirsova', 86)
Romania.connect('Urziceni', 'Vaslui', 142)
Romania.connect('Iasi', 'Vaslui', 92)
Romania.connect('Iasi', 'Neamt', 87)
