from graph import Graph

Romania = Graph()
Romania.add_node('Arad')
Romania.add_node('Bucharest')
Romania.add_node('Craiova')
Romania.add_node('Drobeta')
Romania.add_node('Eforie')
Romania.add_node('Fagaras')
Romania.add_node('Giurgiu')
Romania.add_node('Hirsova')
Romania.add_node('Iasi')
Romania.add_node('Lugoj')
Romania.add_node('Mehadia')
Romania.add_node('Neamt')
Romania.add_node('Oradea')
Romania.add_node('Pitesti')
Romania.add_node('Rimnicu Vilcea')
Romania.add_node('Sibiu')
Romania.add_node('Timisoara')
Romania.add_node('Urziceni')
Romania.add_node('Vaslui')
Romania.add_node('Zerind')
Romania.connect('Oradea', 'Zerind', 71)
Romania.connect('Oradea', 'Sibiu', 151)
Romania.connect('Arad', 'Zerind', 75)
Romania.connect('Arad', 'Sibiu', 140)
Romania.connect('Arad', 'Timisoara', 118)
Romania.connect('Lugoj', 'Timisoara', 111)
Romania.connect('Lugoj', 'Mehadia', 70)
Romania.connect('Drobeta', 'Mehadia', 75)
Romania.connect('Drobeta', 'Craiova', 120)
Romania.connect('Rimnicu Vilcea', 'Craiova', 146)
Romania.connect('Pitesti', 'Craiova', 138)
Romania.connect('Rimnicu Vilcea', 'Pitesti', 97)
Romania.connect('Rimnicu Vilcea', 'Sibiu', 80)
Romania.connect('Fagaras', 'Sibiu', 99)
Romania.connect('Fagaras', 'Bucharest', 211)
Romania.connect('Pitesti', 'Bucharest', 101)
Romania.connect('Giurgiu', 'Bucharest', 90)
# Romania.connect('Urziceni', 'Bucharest', 85)
Romania.connect('Urziceni', 'Hirsova', 98)
Romania.connect('Eforie', 'Hirsova', 86)
Romania.connect('Urziceni', 'Vaslui', 142)
Romania.connect('Iasi', 'Vaslui', 92)
Romania.connect('Iasi', 'Neamt', 87)
